framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messenger_delayed_exchange
                        type: x-delayed-message
                        arguments:
                            x-delayed-type: direct
                    queues:
                        messenger_target_queue:
                            binding_keys: [target_queue]

        routing:
            'App\Message\SimpleMessage': async
