version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_playground
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./rabbitmq_delayed_message_exchange-3.10.2.ez:/plugins/rabbitmq_delayed_message_exchange-3.10.2.ez"

  php-service:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php-container
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/project
      - ./docker/php/messenger-worker.conf:/etc/supervisor/conf.d/messenger-worker.conf